### YamlMime:ManagedReference
items:
- uid: AssemblerLib.ExogenousSettings
  commentId: T:AssemblerLib.ExogenousSettings
  id: ExogenousSettings
  parent: AssemblerLib
  children:
  - AssemblerLib.ExogenousSettings.#ctor(System.Collections.Generic.List{Rhino.Geometry.Mesh},System.Int32,AssemblerLib.Field,System.Double,Rhino.Geometry.Box)
  - AssemblerLib.ExogenousSettings.environmentMeshes
  - AssemblerLib.ExogenousSettings.environmentMode
  - AssemblerLib.ExogenousSettings.field
  - AssemblerLib.ExogenousSettings.fieldScalarThreshold
  - AssemblerLib.ExogenousSettings.sandBox
  langs:
  - csharp
  - vb
  name: ExogenousSettings
  nameWithType: ExogenousSettings
  fullName: AssemblerLib.ExogenousSettings
  type: Struct
  source:
    remote:
      path: C:/Users/aless/Documents/@ code/GH code/@ Assembler/Assembler/AssemblerLib/ExogenousSettings.cs
    id: ExogenousSettings
    path: ExogenousSettings.cs
    startLine: 5
  assemblies:
  - AssemblerLib
  namespace: AssemblerLib
  syntax:
    content: public struct ExogenousSettings
    content.vb: Public Structure ExogenousSettings
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetType
  modifiers.csharp:
  - public
  - struct
  modifiers.vb:
  - Public
  - Structure
- uid: AssemblerLib.ExogenousSettings.environmentMeshes
  commentId: F:AssemblerLib.ExogenousSettings.environmentMeshes
  id: environmentMeshes
  parent: AssemblerLib.ExogenousSettings
  langs:
  - csharp
  - vb
  name: environmentMeshes
  nameWithType: ExogenousSettings.environmentMeshes
  fullName: AssemblerLib.ExogenousSettings.environmentMeshes
  type: Field
  source:
    remote:
      path: C:/Users/aless/Documents/@ code/GH code/@ Assembler/Assembler/AssemblerLib/ExogenousSettings.cs
    id: environmentMeshes
    path: ExogenousSettings.cs
    startLine: 7
  assemblies:
  - AssemblerLib
  namespace: AssemblerLib
  syntax:
    content: public List<Mesh> environmentMeshes
    return:
      type: System.Collections.Generic.List{Rhino.Geometry.Mesh}
    content.vb: Public environmentMeshes As List(Of Mesh)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: AssemblerLib.ExogenousSettings.environmentMode
  commentId: F:AssemblerLib.ExogenousSettings.environmentMode
  id: environmentMode
  parent: AssemblerLib.ExogenousSettings
  langs:
  - csharp
  - vb
  name: environmentMode
  nameWithType: ExogenousSettings.environmentMode
  fullName: AssemblerLib.ExogenousSettings.environmentMode
  type: Field
  source:
    remote:
      path: C:/Users/aless/Documents/@ code/GH code/@ Assembler/Assembler/AssemblerLib/ExogenousSettings.cs
    id: environmentMode
    path: ExogenousSettings.cs
    startLine: 8
  assemblies:
  - AssemblerLib
  namespace: AssemblerLib
  syntax:
    content: public int environmentMode
    return:
      type: System.Int32
    content.vb: Public environmentMode As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: AssemblerLib.ExogenousSettings.field
  commentId: F:AssemblerLib.ExogenousSettings.field
  id: field
  parent: AssemblerLib.ExogenousSettings
  langs:
  - csharp
  - vb
  name: field
  nameWithType: ExogenousSettings.field
  fullName: AssemblerLib.ExogenousSettings.field
  type: Field
  source:
    remote:
      path: C:/Users/aless/Documents/@ code/GH code/@ Assembler/Assembler/AssemblerLib/ExogenousSettings.cs
    id: field
    path: ExogenousSettings.cs
    startLine: 9
  assemblies:
  - AssemblerLib
  namespace: AssemblerLib
  syntax:
    content: public Field field
    return:
      type: AssemblerLib.Field
    content.vb: Public field As Field
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: AssemblerLib.ExogenousSettings.fieldScalarThreshold
  commentId: F:AssemblerLib.ExogenousSettings.fieldScalarThreshold
  id: fieldScalarThreshold
  parent: AssemblerLib.ExogenousSettings
  langs:
  - csharp
  - vb
  name: fieldScalarThreshold
  nameWithType: ExogenousSettings.fieldScalarThreshold
  fullName: AssemblerLib.ExogenousSettings.fieldScalarThreshold
  type: Field
  source:
    remote:
      path: C:/Users/aless/Documents/@ code/GH code/@ Assembler/Assembler/AssemblerLib/ExogenousSettings.cs
    id: fieldScalarThreshold
    path: ExogenousSettings.cs
    startLine: 10
  assemblies:
  - AssemblerLib
  namespace: AssemblerLib
  syntax:
    content: public double fieldScalarThreshold
    return:
      type: System.Double
    content.vb: Public fieldScalarThreshold As Double
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: AssemblerLib.ExogenousSettings.sandBox
  commentId: F:AssemblerLib.ExogenousSettings.sandBox
  id: sandBox
  parent: AssemblerLib.ExogenousSettings
  langs:
  - csharp
  - vb
  name: sandBox
  nameWithType: ExogenousSettings.sandBox
  fullName: AssemblerLib.ExogenousSettings.sandBox
  type: Field
  source:
    remote:
      path: C:/Users/aless/Documents/@ code/GH code/@ Assembler/Assembler/AssemblerLib/ExogenousSettings.cs
    id: sandBox
    path: ExogenousSettings.cs
    startLine: 11
  assemblies:
  - AssemblerLib
  namespace: AssemblerLib
  syntax:
    content: public Box sandBox
    return:
      type: Rhino.Geometry.Box
    content.vb: Public sandBox As Box
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: AssemblerLib.ExogenousSettings.#ctor(System.Collections.Generic.List{Rhino.Geometry.Mesh},System.Int32,AssemblerLib.Field,System.Double,Rhino.Geometry.Box)
  commentId: M:AssemblerLib.ExogenousSettings.#ctor(System.Collections.Generic.List{Rhino.Geometry.Mesh},System.Int32,AssemblerLib.Field,System.Double,Rhino.Geometry.Box)
  id: '#ctor(System.Collections.Generic.List{Rhino.Geometry.Mesh},System.Int32,AssemblerLib.Field,System.Double,Rhino.Geometry.Box)'
  parent: AssemblerLib.ExogenousSettings
  langs:
  - csharp
  - vb
  name: ExogenousSettings(List<Mesh>, Int32, Field, Double, Box)
  nameWithType: ExogenousSettings.ExogenousSettings(List<Mesh>, Int32, Field, Double, Box)
  fullName: AssemblerLib.ExogenousSettings.ExogenousSettings(System.Collections.Generic.List<Rhino.Geometry.Mesh>, System.Int32, AssemblerLib.Field, System.Double, Rhino.Geometry.Box)
  type: Constructor
  source:
    remote:
      path: C:/Users/aless/Documents/@ code/GH code/@ Assembler/Assembler/AssemblerLib/ExogenousSettings.cs
    id: .ctor
    path: ExogenousSettings.cs
    startLine: 13
  assemblies:
  - AssemblerLib
  namespace: AssemblerLib
  syntax:
    content: public ExogenousSettings(List<Mesh> environmentMeshes, int environmentMode, Field field, double fieldScalarThreshold, Box sandBox)
    parameters:
    - id: environmentMeshes
      type: System.Collections.Generic.List{Rhino.Geometry.Mesh}
    - id: environmentMode
      type: System.Int32
    - id: field
      type: AssemblerLib.Field
    - id: fieldScalarThreshold
      type: System.Double
    - id: sandBox
      type: Rhino.Geometry.Box
    content.vb: Public Sub New(environmentMeshes As List(Of Mesh), environmentMode As Integer, field As Field, fieldScalarThreshold As Double, sandBox As Box)
  overload: AssemblerLib.ExogenousSettings.#ctor*
  nameWithType.vb: ExogenousSettings.ExogenousSettings(List(Of Mesh), Int32, Field, Double, Box)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: AssemblerLib.ExogenousSettings.ExogenousSettings(System.Collections.Generic.List(Of Rhino.Geometry.Mesh), System.Int32, AssemblerLib.Field, System.Double, Rhino.Geometry.Box)
  name.vb: ExogenousSettings(List(Of Mesh), Int32, Field, Double, Box)
references:
- uid: AssemblerLib
  commentId: N:AssemblerLib
  name: AssemblerLib
  nameWithType: AssemblerLib
  fullName: AssemblerLib
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  name: Equals(Object)
  nameWithType: ValueType.Equals(Object)
  fullName: System.ValueType.Equals(System.Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    nameWithType: ValueType.Equals
    fullName: System.ValueType.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    nameWithType: ValueType.Equals
    fullName: System.ValueType.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    nameWithType: ValueType.GetHashCode
    fullName: System.ValueType.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    nameWithType: ValueType.GetHashCode
    fullName: System.ValueType.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    nameWithType: ValueType.ToString
    fullName: System.ValueType.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    nameWithType: ValueType.ToString
    fullName: System.ValueType.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Collections.Generic.List{Rhino.Geometry.Mesh}
  commentId: T:System.Collections.Generic.List{Rhino.Geometry.Mesh}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.List`1
  name: List<Mesh>
  nameWithType: List<Mesh>
  fullName: System.Collections.Generic.List<Rhino.Geometry.Mesh>
  nameWithType.vb: List(Of Mesh)
  fullName.vb: System.Collections.Generic.List(Of Rhino.Geometry.Mesh)
  name.vb: List(Of Mesh)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Rhino.Geometry.Mesh
    name: Mesh
    nameWithType: Mesh
    fullName: Rhino.Geometry.Mesh
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Rhino.Geometry.Mesh
    name: Mesh
    nameWithType: Mesh
    fullName: Rhino.Geometry.Mesh
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.List`1
  commentId: T:System.Collections.Generic.List`1
  isExternal: true
  name: List<T>
  nameWithType: List<T>
  fullName: System.Collections.Generic.List<T>
  nameWithType.vb: List(Of T)
  fullName.vb: System.Collections.Generic.List(Of T)
  name.vb: List(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: AssemblerLib.Field
  commentId: T:AssemblerLib.Field
  parent: AssemblerLib
  name: Field
  nameWithType: Field
  fullName: AssemblerLib.Field
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  name: Double
  nameWithType: Double
  fullName: System.Double
- uid: Rhino.Geometry.Box
  commentId: T:Rhino.Geometry.Box
  parent: Rhino.Geometry
  isExternal: true
  name: Box
  nameWithType: Box
  fullName: Rhino.Geometry.Box
- uid: Rhino.Geometry
  commentId: N:Rhino.Geometry
  isExternal: true
  name: Rhino.Geometry
  nameWithType: Rhino.Geometry
  fullName: Rhino.Geometry
- uid: AssemblerLib.ExogenousSettings.#ctor*
  commentId: Overload:AssemblerLib.ExogenousSettings.#ctor
  name: ExogenousSettings
  nameWithType: ExogenousSettings.ExogenousSettings
  fullName: AssemblerLib.ExogenousSettings.ExogenousSettings
